.\" Manpage for rndpwd.
.TH RNDPWD "1" "2015-2016" "rndpwd" "User Commands"
.SH NAME
rndpwd \- Command-line and Web-service Random Password Generator
.SH DESCRIPTION
rndpwd is a command\-line and web-service tool to generate random passwords
.SS "Usage:"
.IP
rndpwd [flags]
rndpwd [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-s\fR, \fB\-\-serverMode\fR=\fI10\fR: Set this to true to start a RESTful API server mode
.HP
\fB\-u\fR, \fB\-\-serverAddress\fR=\fI10\fR: HTTP API address for server mode (ip:port) or just (:port)
.HP
\fB\-l\fR, \fB\-\-length\fR=\fI16\fR: Length of each password (number of characters or bytes)
.HP
\fB\-c\fR, \fB\-\-charset=\fR"!#$%&()*+,\-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_abcdefghijklmnopqrstuvwxyz{|}~": Characters to use to generate a password
.HP
\fB\-q\fR, \fB\-\-quantity\fR=\fI10\fR: Number of passwords to generate
.HP
\fB\-o\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: NONE, EMERGENCY, ALERT, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
.PP
Use "rndpwd [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
Nicola Asuni (info@tecnick.com)
.SH COPYRIGHT
(c) 2015-2016 Nicola Asuni - Tecnick.com LTD
