language: go

sudo: false

go:
  - 1.5
  - tip

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - make deps

script:
  - make qa

after_failure:
  - cat ./target/test/report.xml

after_script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
