language: go

sudo: false

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

go:
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

addons:
  apt:
    packages:
    - devscripts
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make
    - dh-golang

before_install:
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN}; fi;
  - go get github.com/mattn/goveralls

before_script:
  - make deps

script:
  - make qa
  #- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_GO_VERSION" = "1.7" ] && [ -n "$BT_APIUSER" ]; then make bintray APIUSER=${BT_APIUSER} APIKEY=${BT_APIKEY}; fi;

after_failure:
  - cat ./target/test/report.xml

after_success:
  - if [ "$TRAVIS_GO_VERSION" = "1.7" ]; then $HOME/gopath/bin/goveralls -covermode=count -coverprofile=target/report/coverage.out -service=travis-ci; fi;
