language: go

sudo: false

go:
  - 1.5
  - tip

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - make deps

script:
  - make qa

after_failure:
  - cat ./target/test/report.xml

after_script:
  - if [ "$TRAVIS_GO_VERSION" = "1.5" ]; then $HOME/gopath/bin/goveralls -covermode=count -coverprofile=target/report/coverage.out -service=travis-ci; fi;
