version: '3.3'

services:
  rndpwd_integration:
    container_name: rndpwd_integration
    build:
      context: .
      dockerfile: test.integration.Dockerfile
    environment:
      DEPLOY_ENV: "int"
    depends_on:
      - rndpwd
      - rndpwd_smocker_ipify
    volumes:
      - ./target/binutil/dockerize:/usr/bin/dockerize

  rndpwd:
    image: tecnickcom/rndpwd:latest
    container_name: rndpwd
    restart: always
    env_file:
      - target/rndpwd.integration.env
    entrypoint: [
        "/usr/bin/dockerize",
        "-wait", "tcp://rndpwd_smocker_ipify:8081",
        "/usr/bin/rndpwd"
    ]
    volumes:
      - ./target/binutil/dockerize:/usr/bin/dockerize

  rndpwd_smocker_ipify:
    container_name: rndpwd_smocker_ipify
    image: thiht/smocker
