openapi: 3.0.3
info:
  title: rndpwd
  description: Public API
  contact:
    email: info@tecnick.com
  license:
    name: Internal use only. All rights reserved.
    url: https://github.com/tecnickcom/rndpwd/blob/main/LICENSE
  version: 1.0.0
servers:
  - url: https://rndpwd:8071/
security:
  - {}
tags:
  - name: ping
    description: Ping this service
  - name: uid
    description: generate a random UID
  - name: random
    description: generate a random values
paths:
  /ping:
    get:
      tags:
        - ping
      summary: Check if the service is reachable
      responses:
        '200':
          description: The service is reachable
          content:
            text/plain:
              schema:
                type: string
                description: OK
  /uid:
    get:
      tags:
        - uid
      summary: Generates a random UID
      responses:
        '200':
          description: Random UID
          content:
            application/json:
              schema:
                type: string
                description: UID
  /password:
    get:
      parameters:
        - $ref: '#/components/parameters/charset'
        - $ref: '#/components/parameters/length'
        - $ref: '#/components/parameters/quantity'
      tags:
        - random
      summary: Generates a list of random passwords
      responses:
        '200':
          description: Random passwords
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                description: random passwords
        '400':
          description: Invalid parameter
components:
  parameters:
    charset:
      in: query
      name: charset
      required: false
      schema:
        type: string
        minLength: 1
        maxLength: 256
        pattern: '^[!"#$%&''()*+,\-./0-9:;<=>?@A-Z\[\\\]^_`a-z{|}~]+$'
      example: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    length:
      description: Password length.
      in: query
      name: length
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 4096
        default: 32
      example: 16
    quantity:
      description: Number passwords to generate.
      in: query
      name: quantity
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 10
      example: 2
