# Dockerfile
#
# Linux development environment
#
# @author      Nicola Asuni <info@tecnick.com>
# @copyright   2015-2016 Nicola Asuni - Tecnick.com LTD
#
# extend the tecnickcom/alldev image defined in
# https://github.com/tecnickcom/alldev
# ------------------------------------------------------------------------------

FROM tecnickcom/alldev
MAINTAINER info@tecnick.com
